# http://docs.ansible.com/ansible/playbooks_environment.html
# environment:
#   http_proxy: http://proxy.example.com:8080
#   NOTE: This is a slightly altered version of the site.yml from the bearded
#   avenger toolkit.  I've removed the elasticsearch bits because it does not
#   run in a container.  Instead of running the ansible role on a vanilla
#   image, you should use the containerized version provided by elastic
---
- name: configure platform
  hosts: localhost
  gather_facts: False
  become: True

  vars_files:
    - "vars/main.yml"
    - "../global_vars.yml"

  vars:
    - GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
    - router_store_args: ''
    - router_hunter_threads: "{{ lookup('env', 'CIF_HUNTER_THREADS') }}"
    - router_hunter_advanced: "{{ lookup('env', 'CIF_HUNTER_ADVANCED') }}"
    - router_gatherer_geo_fqdn: "{{ lookup('env', 'CIF_GATHERER_GEO_FQDN') }}"

  pre_tasks:

    - name: configure python
      raw: sudo apt-get install python-minimal aptitude -y

    - setup:
       filter: ansible_*

    - name: set store fact
      set_fact:
        router_store_store: 'elasticsearch'
        router_store_nodes: "{{ CIF_ES }}"
      when: CIF_ES is defined and CIF_ES != ""

    - name: set build_sdist
      set_fact:
        cif_build_sdist: CIF_ANSIBLE_SDIST
      when: CIF_ANSIBLE_SDIST is defined

    - import_tasks: tasks/main.yml


  roles:
    - { role: csirtgadgets.cif, tags: role-cif }
    - { role: nginx, tags: role-nginx }
